title: "Bootstrap Blog"
baseurl: "http://192.168.178.100:1313/"

languageCode: "en-us"
theme: "hugo-bootstrap"

taxonomies:
  tag: "tags"
  category: "categories"


languages:
  en:
    languageName: "English"
    menu:
      menu:
        - url: "/"
          name: "Home"
          weight: 1
        - url: "/about/"
          name: "About"
          weight: 2
      main2:
        - url: "/test/"
          name: "Test"
          weight: 1